CREATE TABLE [FileAssets].[DailyTweetMedia] AS FILETABLE ON [PRIMARY] FILESTREAM_ON [FilestreamData]
WITH
(
	FILETABLE_DIRECTORY = N'DailyTweetMedia', FILETABLE_COLLATE_FILENAME = Latin1_General_100_CI_AS, FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = [PK__DailyTwe__5A5B77D57E644E40]
)
GO
