CREATE TABLE [FileAssets].[DeletedImagesTempHold] AS FILETABLE ON [PRIMARY] FILESTREAM_ON [FilestreamData]
WITH
(
	FILETABLE_DIRECTORY = N'DeletedImagesTempHold', FILETABLE_COLLATE_FILENAME = Latin1_General_100_CI_AS, FILETABLE_PRIMARY_KEY_CONSTRAINT_NAME = [PK__DeletedImagesTempHold__5A5B77D539F1EC79]
)
GO
